services:
  - type: worker
    name: discord-bot
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install wheel
      pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: PIP_VERSION
        value: "23.0.1"
    autoDeploy: true
    plan: free
    region: oregon
